accordion/urls.py
from django.urls import path
from . import views

app_name = 'accordion'

urlpatterns = [
    path('accordion', views.index, name='index'),
]

booklist/urls.py
from django.urls import path

from . import views

app_name = 'booklist'

urlpatterns = [
    path('', views.index, name='index'),
    path('get_book/<str:query>', views.get_book)
]

landing_page/urls.py
from django.urls import path
from . import views

app_name = 'landing_page'

urlpatterns = [
    path('', views.index, name='index'),
]

login/urls.py
from django.urls import path

from . import views

app_name = 'login'

urlpatterns = [
    path('', views.index, name='index'),
    path('landing', views.landing, name='landing'),
    path('register', views.register, name='register'),
    path('logout', views.logout, name='logout'),
]

nginx/urls.py
from django.urls import path
from . import views

app_name = 'nginx'

urlpatterns = [
    path('', views.index, name='index'),
]

tdd_web/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('landing_page.urls')),
    path('', include('accordion.urls')),
    path('book/', include('booklist.urls')),
    path('login/', include('login.urls')),
    path('load_balancer/', include('nginx.urls')),
]

accordion/models.py
from django.db import models

# Create your models here.

booklist/models.py
from django.db import models

# Create your models here.

landing_page/models.py
from django.db import models
from django.utils import timezone

class Status(models.Model):
    text = models.TextField(max_length=300)
    post_time = models.DateTimeField()

    def save(self, *args, **kwargs):
        ''' to compensate auto date created according to creation date '''
        if not self.id:
            self.post_time = timezone.now()
        
        return super(Status, self).save(*args, **kwargs)

    def __str__(self):
        text_string = self.text
        if len(str(text_string)) > 11:
            text_string = text_string[:11]+'...'
        return "<Status| pk: {}, text: '{}', post-time: {}>".format(self.id, text_string, self.post_time)

login/models.py
from django.db import models

# Create your models here.

nginx/models.py
from django.db import models

# Create your models here.

landing_page/forms.py
from django import forms
from django.forms import ModelForm, Textarea
from .models import Status

class StatusForm(ModelForm):

    class Meta:
        model = Status
        fields = ['text']
        error_messages = {
            'text': {
                'max_length': 'There are more than 300 character'
            }
        }
        widgets = {
            'text': Textarea(
                attrs={
                    'style': "min-width: 100%; max-width: 100%; min-height: 50px; max-height: 200px; border-radius: 10px; height: 100px; padding: 5px 10px; "
                    }
                )
        }

login/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm

class LoginForm(forms.Form):
    username = forms.CharField(max_length=30)
    password = forms.CharField(max_length=30, widget=forms.PasswordInput)

class RegistrationForm(UserCreationForm):
    email = forms.EmailField()
    first_name = forms.CharField(max_length=30)
    last_name = forms.CharField(max_length=30)

accordion/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'accordion/accordion.html')

booklist/views.py
from django.shortcuts import render, redirect
from django.http.response import JsonResponse
import requests

# Create your views here.
def index(request):
    return render(request, 'booklist/index.html')

def get_book(request, query):
    response = requests.get('https://www.googleapis.com/books/v1/volumes?q='+query)
    print(response)
    books = response.json()
    return JsonResponse(books)

landing_page/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, reverse
from .models import Status
from .forms import StatusForm

def index(request):
    
    statuses = Status.objects.all().order_by('-post_time')
    status_form = StatusForm()

    if request.method == 'POST':

        status_form = StatusForm(request.POST)

        if status_form.is_valid():
            
            status_form.save()

            return HttpResponseRedirect(reverse('landing_page:index'))  

    return render(request, 'landing_page/index.html', { 'statuses': statuses, 'status_form': status_form })

login/views.py
from django.shortcuts import render, reverse, redirect
from django.contrib.auth import authenticate, login, logout as logout_auth
from django.contrib.auth.models import User
from .forms import LoginForm, RegistrationForm

# Create your views here.
def index(request):
    login_form = LoginForm()

    if request.user.is_authenticated:
        return redirect(reverse('login:landing'))

    if request.method == 'POST':

        login_form = LoginForm(request.POST)
        
        if login_form.is_valid():

            user = authenticate(
                request,
                username=login_form.cleaned_data['username'],
                password=login_form.cleaned_data['password']
            )

            if user is not None:
                login(request, user)
                return redirect(reverse('login:landing'))
            
            login_form.add_error(None, 'user not registered')
    
    return render(request, 'login/login.html', {'form': login_form})

def register(request):
    regis_form = RegistrationForm()

    if request.method == 'POST':

        regis_form = RegistrationForm(request.POST, request)

        if regis_form.is_valid():
            
            User.objects.create_user(
                username=regis_form.cleaned_data['username'],
                email=regis_form.cleaned_data['email'],
                first_name=regis_form.cleaned_data['first_name'],
                last_name=regis_form.cleaned_data['last_name'],
                password=regis_form.cleaned_data['password1'],
            )

            return redirect(reverse('login:index'))

    return render(request, 'login/register.html', {'form': regis_form})

def logout(request):
    logout_auth(request)
    return redirect(reverse('login:landing'))

def landing(request):
    return render(request, 'login/landing.html')

nginx/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    return render(request, 'nginx/index.html')

accordion/templates/accordion/accordion.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
    <link href="{% static 'accordion/css/accordion.css' %}" rel='stylesheet' type='text/css'>
{% endblock style %}

{% block content %}
    <section class='wrapper'>
        <h1>Hello<span>| This is ME</span></h1>
    </section>
    <section class='acc-wrapper'>
        <div class='accordion'>
            <h2 class='acc-header'>Activity</h2>
            <div class='acc-content'>
                <p>I'm currently enrolled on cs bachelor program at Universitas Indonesia.</p>
            </div>
        </div>
        <div class='accordion'>
            <h2 class='acc-header'>Experience</h2>
            <div class='acc-content'>
                <p>Quite nothingness exactly</p>
            </div>
        </div>
        <div class='accordion'>
            <h2 class='acc-header'>Achievement</h2>
            <div class='acc-content'>
                <p>I could achive nothing in my life</p>
            </div>
        </div>
    </section>
{% endblock content %}

booklist/templates/booklist/index.html
{% extends 'base.html' %}
{% load static %}

{% block script %}
    <script src="{% static 'booklist/js/search-book.js' %}"></script>
{% endblock script %}

{% block style %}
    <link href="{% static 'booklist/css/index.css' %}" type="text/css" rel="stylesheet">
{% endblock style %}

{% block content %}
    <section class="wrapper">
        <div>
            <input id='search-bar' type="search" placeholder="search">
        </div>
        <div id="result-table">
            <table>
                <thead>
                    <tr>
                        <th>Judul</th>
                        <th>Penulis</th>
                        <th>Gambar</th>
                    </tr>
                </thead>
                <tbody id="search-result">
                </tbody>
            </table>
        </div>
    </section>
{% endblock content %}

landing_page/templates/landing_page/index.html
{% extends 'base.html' %}
{% load static %}

{% block script %}
{% endblock script %}

{% block content %}
<section class='wrapper'>
    <h1>Halo, apa kabar?</h1>
    <form id="status-form" method="post">
        {% csrf_token %}
        {{ status_form.text.errors }}
        {{ status_form.text }}
        <div>
            <button type="submit" id="status-submit">Post</button>
        </div>
    </form>
    {% if statuses %}
        <section class="status-wrapper">
            {% for status in statuses %}
                <div class="status">
                    {{status.text}}<br>
                    <span class="time">{{status.post_time}}</span>
                </div>
            {% endfor %}
        </section>
</section>
    {% endif %}
{% endblock content %}

login/templates/login/base.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
    <link href="{% static 'login/css/login.css' %}" rel="stylesheet" type="text/css">
{% endblock style %}

login/templates/login/landing.html
{% extends 'login/base.html' %}

{% block content %}
<div class="wrapper">
        {% if user.is_authenticated %}
            <p>Hello, {{ user.get_full_name }}</p>
        {% else %}
            <p>Anda belum login</p>
            <p>Silahkan login</p>
        {% endif %}
    </div>
{% endblock content %}

login/templates/login/login.html
{% extends 'login/base.html' %}

{% block content %}
    <section class="wrapper">
        <form method="post" action="{% url 'login:index' %}">
            {% csrf_token %}
            <table cellpadding="10">
                    {% if form.errors %}
                    <tr>
                        <td colspan="2">Your username and password didn't matched. Please try again.</td>
                    </tr>
                    {% endif %}
                <tr>
                    <td>{{ form.username.label_tag }}</td>
                    <td>{{ form.username }}</td>
                </tr>
                <tr>
                    <td>{{ form.password.label_tag }}</td>
                    <td>{{ form.password }}</td>
                </tr>
            </table>
            <input type="submit" value="login">
        </form>
    </section>
{% endblock content %}

login/templates/login/register.html
{% extends 'login/base.html' %}

{% block content %}
    <div class="wrapper">
        <form method="post" action="{% url 'login:register' %}">
                {% csrf_token %}
                <table cellpadding="10">
                    {% for field in form %}
                        {% if field.errors %}
                            {% for error in field.errors %}
                                <tr id="error"><td colspan="2">{{ error }}</td></tr>
                            {% endfor %}
                        {% endif %}
                        <tr>
                            <td>{{ field.label_tag }}</td>
                            <td>{{ field }}</td>
                        </tr>
                    {% endfor %}
                </table>
                <input type="submit" value="register">
            </form>
    </div>
{% endblock content %}

nginx/templates/nginx/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
  <section class="wrapper flex-container">
    <div class="blog-wrapper">

      <h1>How to use load balancer using NGINX <br> (for Windows)</h1>
      <p>I will tell you how to configure your own nginx on
      be load balancer on your local server.</p>

      <h2>1. Installing NGINX</h2>
      <p>First download nginx from the official 
        <a target="_blank" href="https://nginx.org/en/download.html">webpage</a>.
        Then pick download link for windows. <em>(We recommend you to pick
          either mainline or stable version. Legacy is highly discouraged
          for its old support)</em>
      </p>
      <img src="{% static 'nginx/image/download.png' %}">
      <p>
      Extract the downloaded zip file on project folder <em>(you could extract it wherever you like)</em>
      and run nginx.exe.
      </p>
      <img src="{% static 'nginx/image/nginx-exe-a.png' %}">
      <p>Now run localhost, and your browser supposed to look like this</p>
      <img src="{% static 'nginx/image/nginx_first.png' %}">

      <h2>2. Configure nginx.conf</h>
      <p>
        To make nginx run accordingly, we should configure the nginx.conf. This will tell
        the nginx, how does it suppose to work. We will configure so it will use localhost port 8000
        and 9000 as host server.
      </p>
      <p>
      Copy this code onto your nginx.conf
      </p>
      <div class="code-block">
        <pre><code lang="conf">http {
  include    mime.types;
  index    index.html index.htm index.php;
  upstream localhost {
    server 127.0.0.1:8000;
    server 127.0.0.1:9000;
  }

  server { # simple load balancing
    listen          80;
    server_name     localhost;

    location / {
      proxy_pass      http://localhost;
    }
  }
}</code></pre>
      </div>
      <p>let's ignore the details. What the code basicly tells are "listen on domain localhost for request, then redirect
      it to localhost upstream." Then the code tells nginx to use port 8000 and 9000. Then let nginx do the magic and your web is ready to go.</p>

      <h2>3. Open your localhost</h2>
      <p>On your local cmd, let django to run server on port 8000 and 9000 by using: <code>python manage.py runserver 8000</code>
      and <code>python manage.py runserver 9000</code> on two different console.</p>
      <p>Open your localhost on browser, and watch both console to check as tis change from port 8000 and 9000.</p>
      <img src="{% static 'nginx/image/port_a.png' %}">

      <h2>4. Enjoy using nginx</h2>
      <p>Ah... yeah, now you could use nginx on localhost. <em>(don't ask me on how to set it up for deployment)</em></p>
    </div>
  </section>
{% endblock content %}

tdd_web/templates/base.html
{% load static %}
<!DOCTYPE html>
<html>
    <head>
        <link href="{% static 'base.css' %}" rel="stylesheet" type="text/css">
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
        {% block style %}
        {% endblock style %}
        <script src="{% static 'accordion/js/color-theme.js' %}"></script>
        <script src="{% static 'accordion/js/accordion.js' %}"></script>
        {% block script %}
        {% endblock script %}
    </head>
    <body>
        <nav>
            <ul>
                <li><a href="{% url 'landing_page:index' %}">Home</a></li>
                <li><a href="{% url 'accordion:index' %}">Accordion</a></li>
                <li><a href="{% url 'booklist:index' %}">Books</a></li>
                {% if user.is_authenticated %}
                    <li><a href="{% url 'login:logout' %}">Logout</a></li>
                {% else %}
                    <li><a href="{% url 'login:index' %}">Login</a></li>
                    <li><a href="{% url 'login:register' %}">Register</a></li>
                {% endif %}
            </ul>
            <div class="accordion">
                <h3 class="acc-header" id="theme_change">Color Theme</h3>
                <div class="acc-content">
                    <input class="color-change" color-value="default" id="default_theme_check" type="checkbox">
                    <input class="color-change" color-value="dark" id="dark_theme_check" type="checkbox">
                    <input class="color-change" color-value="light" id="light_theme_check" type="checkbox">
                </div>
            </div>
        </nav>
        {% block content %}
        {% endblock content %}
    </body>
</html>